### ISSUE TITLE
Support for angle, resolution, frequency and time units

### ISSUE THREAD

**Issue by niksy** [jedmao/parse-css-dimension#1]
Would it make sense to have support for [angle units](https://developer.mozilla.org/en-US/docs/Web/CSS/angle), [resolution units](https://developer.mozilla.org/en-US/docs/Web/CSS/resolution), [frequency units](https://developer.mozilla.org/en-US/docs/Web/CSS/frequency) and [time units](https://developer.mozilla.org/en-US/docs/Web/CSS/time)? Maybe through separate package like css-length-units?

This would make this package really versatile when it comes to parsing any arbitrary string which can contain known units.

**Comment by jedmao** [comment]
Yes, that would definitely make sense for this package, as those are all considered CSS "dimensions"; however, I have no plans to implement it. Willing to accept PRs.

**Comment by niksy** [comment]
@jedmao OK, I’ve created the PR so you can review it.

**Comment by jedmao** [comment]
@niksy, published as version 1.1.0. Thanks!
